# Practical_6: Numpy

In [3]:
import numpy as np

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.


In [11]:
arra1=np.arange(1,11)
arra1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.


In [15]:
arr2 = np.zeros((3, 3))
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.


In [17]:
# Exercise 3
arr3 = np.linspace(0, 5, 10)
arr3

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])


---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.


In [23]:
# Exercise 4
matrixarr= np.eye(5)
print("\nExercise 4:\n", matrixarr)



Exercise 4:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]



---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.


In [29]:
# Exercise 5
randomarr=np.random.rand(4,4)
randomarr

array([[0.57269586, 0.79341244, 0.2995988 , 0.48985148],
       [0.30397438, 0.17627025, 0.51146736, 0.14493555],
       [0.47887653, 0.33734178, 0.49356935, 0.47459249],
       [0.01241917, 0.47434067, 0.57512843, 0.55441923]])


---

### Exercise 6:
Find the shape of a NumPy array.


In [31]:
# Exercise 6
numarr=np.arange(1,5)
print(numarr.shape)

(4,)



---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.


In [33]:
# Exercise 7
arr7 = np.arange(16).reshape(4, 4)
arr7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])


---

### Exercise 8:
Find the data type of the elements in a NumPy array.


In [35]:
# Exercise 8
arr7 = np.arange(16).reshape(4, 4)
type(arr7)

numpy.ndarray


---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.


In [41]:
# Exercise 9
arr9 = np.arange(1, 101)
evens = arr9[arr9 % 2 == 0]
print("Exercise 9:", evens)



Exercise 9: [  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]



---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.


In [47]:
# Exercise 10
arr10 = np.random.randint(10, 50, size=(6, 6))
print("\nExercise 10:\n", arr10)


Exercise 10:
 [[34 30 22 40 33 34]
 [49 40 30 19 48 17]
 [36 15 31 42 22 20]
 [49 32 25 37 39 34]
 [49 25 15 15 18 31]
 [18 34 46 45 11 43]]



---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.


In [49]:
# Exercise 11
submatrix = arr10[1:3, 2:4]
print("\nExercise 11:\n", submatrix)



Exercise 11:
 [[30 19]
 [31 42]]



---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.


In [57]:
# Exercise 12
submatrix = arr10[1:3, 2:4]
print("\nExercise 11:\n", submatrix)
submatrix.sum()


Exercise 11:
 [[30 19]
 [31 42]]


122


---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.


In [59]:
# Exercise 13
print("Mean:", np.mean(arr10))
print("Median:", np.median(arr10))
print("Std:", np.std(arr10))


Mean: 31.333333333333332
Median: 32.5
Std: 11.147994338793762



---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.


In [61]:
# Exercise 14
print("Max:", arr10.max())
print("Min:", arr10.min())


Max: 49
Min: 11



---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.


In [65]:
# Exercise 15
arr15 = np.random.randint(0, 100, 20)
print(arr15.argmax())


3



---

### Exercise 16:
Create a NumPy array and reverse its elements.


In [67]:
# Exercise 16
print("\nExercise 16:", arr15[::-1])


Exercise 16: [61 72 62 42  7 18 68 63 37 76 19 44 51  1 16 64 84 27 14 30]



---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [69]:
# Exercise 17
mat1 = np.random.randint(1, 5, (3, 3))
mat2 = np.random.randint(1, 5, (3, 3))
print("\nExercise 17:\n", mat1 * mat2)



Exercise 17:
 [[16  4  8]
 [12 12  8]
 [12 12  4]]



---

### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [73]:
# Exercise 18
arr18 = np.diag([1, 2, 3, 4])
print(
    arr18)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]



---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [77]:
# Exercise 19
print(np.dot(mat1, mat2))

[[38 30 32]
 [36 28 32]
 [25 19 22]]



---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.


In [79]:
# Exercise 20
print("\nExercise 20:", mat1.flatten())



Exercise 20: [4 2 4 4 4 2 3 3 1]



---

### Exercise 21:
Stack two NumPy arrays vertically.


In [83]:
# Exercise 21
print("\nExercise 21:\n", np.vstack((mat1, mat2)))


Exercise 21:
 [[4 2 4]
 [4 4 2]
 [3 3 1]
 [4 2 2]
 [3 3 4]
 [4 4 4]]



---

### Exercise 22:
Stack two NumPy arrays horizontally.


In [87]:
# Exercise 22
print(np.hstack((mat1, mat2)))

[[4 2 4 4 2 2]
 [4 4 2 3 3 4]
 [3 3 1 4 4 4]]



---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.


In [89]:
# Exercise 23
print("\nExercise 23:\n", np.split(arr7, 4))


Exercise 23:
 [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]



---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.


In [91]:
# Exercise 24
arr24 = np.random.random(5)
print("\nExercise 24:", np.round(arr24, 2))


Exercise 24: [0.58 0.01 0.46 0.54 0.46]



---

### Exercise 25:
Find the unique elements of a NumPy array.


In [95]:
# Exercise 25
arr25 = np.array([1, 2, 2, 3, 4, 4, 4])
print(np.unique(arr25))

[1 2 3 4]



---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.


In [103]:
# Exercise 26
arrless= np.random.randint(0, 100, 10)
print(np.clip(arrless, 20, 80))

[80 56 20 80 42 74 21 20 40 20]



---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.


In [105]:
# Exercise 27
print(np.cumsum(arrless))

[ 81 137 141 236 278 352 373 383 423 432]



---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.


In [111]:
# Exercise 28
print("\n non zero", np.count_nonzero(arrless))


 non zero 10



---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.


In [113]:
# Exercise 29
print(np.sort(arrless))

[ 4  9 10 21 40 42 56 74 81 95]



---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.


In [115]:
# Exercise 30
print("\nExercise 30:")
print("Row sums:", arr10.sum(axis=1))
print("Column sums:", arr10.sum(axis=0))


Exercise 30:
Row sums: [193 203 166 216 153 197]
Column sums: [235 176 169 198 171 179]



---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).


In [119]:
# Exercise 31
arr31 = np.random.random((3, 3))
normalized = (arr31 - arr31.min()) / (arr31.max() - arr31.min())
print(normalized)


[[0.26757941 0.         0.53988097]
 [0.1999638  1.         0.4143454 ]
 [0.52477431 0.86089603 0.59318215]]



---

### Exercise 32:
Create two NumPy arrays and find the dot product.


In [123]:
# Exercise 32
vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])
print(np.dot(vec1, vec2))

32



---

### Exercise 33:
Find the trace of a square NumPy matrix.


In [125]:
# Exercise 33
print(np.trace(arr10))

203



---

### Exercise 34:
Create a 2D array and swap two rows.


In [127]:
# Exercise 34
arr2D = arr10.copy()
arr2D[[1, 2]] = arr2D[[2, 1]]
arr2D

array([[34, 30, 22, 40, 33, 34],
       [36, 15, 31, 42, 22, 20],
       [49, 40, 30, 19, 48, 17],
       [49, 32, 25, 37, 39, 34],
       [49, 25, 15, 15, 18, 31],
       [18, 34, 46, 45, 11, 43]])


---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.


In [129]:
# Exercise 35
arr35 = np.arange(5).reshape(-1, 1)
print(arr35)

[[0]
 [1]
 [2]
 [3]
 [4]]



---

### Exercise 36:
Find the determinant of a 3x3 matrix.


In [133]:
# Exercise 36
mat36 = np.random.randint(1, 10, (3, 3))
print(np.linalg.det(mat36))

80.99999999999996



---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.


In [137]:
# Exercise 37
mat37 = np.array([[4, 2], [1, 3]])
eigenvalues, eigenvectors = np.linalg.eig(mat37)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]



---

### Exercise 38:
Solve a system of linear equations using NumPy.


In [141]:
# Exercise 38
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
print(np.linalg.solve(A, b))

[2. 3.]



---

### Exercise 39:
Add Gaussian noise to a NumPy array.


In [145]:
# Exercise 39
arr39 = np.zeros(10) + 5
noise = np.random.normal(0, 1, 10)
print(arr39 + noise)

[4.78942086 6.11568671 5.04289689 6.01743529 5.8693113  5.45438417
 4.71881842 3.24689212 3.96900588 4.62040726]



---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.


In [147]:
# Exercise 40
print(np.diag(arr10))

[34 40 31 37 18 43]



---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.


In [151]:
# Exercise 41
arrclip = np.random.randint(0, 100, 100)
print(np.clip(arrclip, 10, 50))

[50 50 14 36 50 50 10 10 50 50 50 50 50 15 50 20 50 50 15 50 50 50 50 40
 10 10 28 50 50 28 10 10 29 10 30 50 16 10 35 22 35 12 21 50 50 39 50 50
 50 11 10 50 42 50 50 23 50 10 50 50 10 13 33 50 50 12 50 50 28 50 40 50
 50 33 36 50 50 10 50 35 27 50 32 50 11 50 50 50 50 44 50 50 50 50 20 50
 50 50 40 15]



---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.


In [ ]:
# Exercise 42


---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.


In [ ]:
# Exercise 43


---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.


In [ ]:
# Exercise 44


---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.


In [ ]:
# Exercise 45


---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.


In [ ]:
# Exercise 46


---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.


In [ ]:
# Exercise 47


---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.


In [ ]:
# Exercise 48


---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.


In [ ]:
# Exercise 49


---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.


In [ ]:
# Exercise 50


---

### Exercise 51:
Convert a NumPy array of radians to degrees.


In [ ]:
# Exercise 51


---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.


In [ ]:
# Exercise 52


---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.


In [ ]:
# Exercise 53


---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.


In [ ]:
# Exercise 54


---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).


In [ ]:
# Exercise 55


---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.


In [ ]:
# Exercise 56


---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.


In [ ]:
# Exercise 57


---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.


In [ ]:
# Exercise 58


---

### Exercise 59:
Compute the Frobenius norm of a matrix.


In [ ]:
# Exercise 59


---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.


In [ ]:
# Exercise 60


---